name: Terraform Check

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init and Validate (Day1)
        run: |
          cd day1
          terraform init
          terraform validate

      - name: Terraform Init and Validate (Day2)
        run: |
          cd day2
          terraform init
          terraform validate

      - name: Terraform Init and Validate (Day3)
        run: |
          cd day3
          terraform init
          terraform validate
