name: Terraform Check

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          cd day1 && terraform init
          cd ../day2 && terraform init
          cd ../day3 && terraform init
          cd ../day4 && terraform init

      - name: Terraform Validate
        run: |
          cd day1 && terraform validate
          cd ../day2 && terraform validate
          cd ../day3 && terraform validate
          cd ../day4 && terraform validate
